title:            Ivo's World
description:      This is my personal website. Hope it helps in your developer search.

disqus_shortname: ivocosme
reading_time:     true
words_per_minute: 180
logo:             images/logo.png
excerpt_separator: <!--more-->

url: https://ivocosme.github.io

menu:
  - title: 'Ivo'
    url: '/about'
  - title: 'Blog'
    url: '/'
  - title: 'Posts'
    url: '/posts'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'

owner:
  name:           Ivo Cosme
  title:          Mobile Software Engineer
  site:           https://ivocosme.github.io
  avatar:         images/avatar.jpg
  bio:            "Ivo is a Mobile Software Engineer. With a few professional years now, lots and lots of hard work and developer dedication, he’s now like most Senior Software Engineers out there... He knows that the things he does know are (yet!) far from the amount of things that he does not know."
  bio_sentence: "<i>In programming, the hard part isn’t solving problems, but deciding what problems to solve.</i> - (Paul Graham)"
  email:          ivocosme@gmail.com
  twitter: biktor
  github: ivocosme

twitter:

social:
  - title: "github"
    url: "https://github.com/ivocosme"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/ivocosme"
  - title: "twitter"
    url: "https://twitter.com/biktor"
  - title: "envelope"
    url: "mailto:ivocosme@gmail.com"

background:

google_analytics: UA-106538846-1
google_verify:
bing_verify:

timezone:    Europe/Lisbon
locale:      pt_PT
future:      false
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:  /:title/

paginate: 5

float_share: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
